# Introduction to NumPy
## A Python List Is More Than Just a List

In [1]:
import numpy as np
np.__version__


'2.2.1'

In [2]:
# Basic loop
result = 0
for i in range(10):
    result += i
result

45

## Creating Arrays from Python Lists

In [3]:
# Heterogeneous Python list
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [4]:
# NumPy array is homogeneous, so it upcast the ints to float
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
# You can also explicitly set the data type
np.array([1.1, 2, 3, 4], dtype='int32')

array([1, 2, 3, 4], dtype=int32)

In [6]:
# Multidimensional arrays
multi = np.array([range(i, i + 3) for i in [2, 4, 6]])
multi


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
multi[0]

array([2, 3, 4])

In [8]:
multi[1,2]
# or multi[1][2]

np.int64(6)

## Creating Arrays from Scratch

In [9]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# Create an array filled with a linear sequence
np.arange(0, 20, 2)
# equals to np.array(range(0, 20, 2))


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
# Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.89513914,  0.73794128,  0.09161192],
       [-1.29090392, -0.62877965, -0.2600634 ],
       [-1.17609842,  0.96121791, -0.3382688 ]])

In [13]:
# Create a 3x3 array of random integers in the inrerval [0,10)
np.random.randint(0,10,(3,3))

array([[5, 6, 3],
       [6, 1, 5],
       [6, 5, 8]])

In [14]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Slicing: Acessing Subrarrays
```python
x[start:stop:step]
```
### One-dimensional subarrays

In [15]:
# when step is negative, start should be greater than stop
x = np.arange(0,10,1)
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Multidimensional subarrays

In [16]:
x2 = np.random.randint(0,10,(5,5))
x2[:2, :3] # first two rows, first three columns

array([[5, 0, 9],
       [4, 0, 2]])

### Subarrays return views (pointers), not copies

In [17]:
print(x2)
print('--------------')
x2_sub = x2[:2,:2]
print(x2_sub)
print('--------------')
x2_sub[0,0] = 99
print(x2_sub)
print('--------------')
print(x2)


[[5 0 9 0 6]
 [4 0 2 9 3]
 [1 9 4 4 8]
 [8 2 6 2 6]
 [5 2 6 6 0]]
--------------
[[5 0]
 [4 0]]
--------------
[[99  0]
 [ 4  0]]
--------------
[[99  0  9  0  6]
 [ 4  0  2  9  3]
 [ 1  9  4  4  8]
 [ 8  2  6  2  6]
 [ 5  2  6  6  0]]


In [18]:
# if you want to copy, you can use .copy
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)
print('--------------')
x2_sub_copy[0,0] = 42
print(x2_sub_copy)
print('--------------')
print(x2)

[[99  0]
 [ 4  0]]
--------------
[[42  0]
 [ 4  0]]
--------------
[[99  0  9  0  6]
 [ 4  0  2  9  3]
 [ 1  9  4  4  8]
 [ 8  2  6  2  6]
 [ 5  2  6  6  0]]


## Array Concatenation and Splitting
### Concatenetaion of arrays


In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y,y])

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [20]:
# The default direction is zero, but you can change it
grid = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([grid,grid],axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [21]:
# you can also use vstack or hstack
print('Vstack:\n',np.vstack([x,grid]))
print('Hstack:\n',np.hstack([[[99],[99]],grid]))


Vstack:
 [[1 2 3]
 [1 2 3]
 [4 5 6]]
Hstack:
 [[99  1  2  3]
 [99  4  5  6]]


## Aggregations: Min, Max, and Everything in Between

In [22]:
L = np.random.rand(100)
sum(L)

np.float64(49.20688595234928)

In [23]:
np.sum(L)

np.float64(49.20688595234929)

In [24]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

39.1 ms ± 67.6 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
202 μs ± 3.35 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [25]:
np.min(big_array) == big_array.min()

np.True_

In [26]:
np.max(big_array) == big_array.max()

np.True_

In [27]:
M = np.random.random((3,4))
print(M)
print('Min = ',M.min())

[[0.7378103  0.07325801 0.48568213 0.14417891]
 [0.54286447 0.87306526 0.01347715 0.93241897]
 [0.30276905 0.98491018 0.51845942 0.36421111]]
Min =  0.01347715343874245


In [28]:
# Find the mininum value within each column by specificing axis = 0
print(M.min(axis=0))

[0.30276905 0.07325801 0.01347715 0.14417891]


In [29]:
# Find the maximum value within each row by specificing axis = 1
print(M.max(axis=1))

[0.7378103  0.93241897 0.98491018]


In [30]:
L[np.argmin(L)] == np.min(L) == L[L.argmin()]

np.True_

In [33]:
np.percentile(L,50) == np.median(L)

np.True_

## Sorting Arrays

In [36]:
x = np.random.randint(0,10,10)
print(x)
print('--------------')
x.sort()
print(x)

[4 0 5 5 8 1 1 5 5 9]
--------------
[0 1 1 4 5 5 5 5 8 9]


In [37]:
x = np.random.randint(0,10,10)
i = np.argsort(x)
print(x[i])

[0 0 1 2 2 4 6 6 8 9]
